name: Trivy scan with severity set to HIGH
on:
    push:
        branches:
          - 'release/v[0-9]+.[0-9]+'
env:
  ifVulnerable: false
jobs:
    Check_Branch:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: Build an image from Dockerfile
            run: |
              docker build -t docker.io/my-organization/my-app:${{github.sha}} .
          - name: Run Trivy vulnerability scanner
            id: trivy
            uses: aquasecurity/trivy-action@master
            with:
              image-ref: 'docker.io/my-organization/my-app:${{github.sha}}'
              format: 'table'
              exit-code: '0'
              ignore-unfixed: true
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'
              output: 'trivy-results.txt'
          - name: Check and Trivy results
            run: |
              if grep -q "CRITICAL" trivy-results.txt; then
                echo "ifVulnerable=true" >> $GITHUB_ENV                
                cat trivy-results.txt
              fi
          - name: Vulnerability Found
            if: ${{env.ifVulnerable == 'true'}}
            id: slack
            uses: slackapi/slack-github-action@v1.26.0
            with:
              payload: |
                {
                  "text": "e1221870",
                  "blocks": 
                    [
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": "New request"
                        }
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Ref:*\n${{github.ref}}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Event:*\n${{github.event_name}}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Actions URL:*\n<https://github.com/xwen028/go-fortune>"
                          }
                        ]
                      }
                    ]
                }
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
